version: "3.7"

services:
  postgres:
    image: postgres:15 # You can use other version
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/data/libma/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0.5 # You can use other version
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ~/data/libma/redis:/data
  libma:
    image: hungtpplay/libma:local
    container_name: libma
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8000
      - PREFORK=false
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["go", "run", "main.go"]